name: Test setup-node caching npm
on: [workflow_dispatch]
jobs:
  run:
    name: Node test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest]
        version: [ '14.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate lock file
      shell: pwsh
      run: |
        npm install
        Remove-Item node_modules -Force -Recurse
        npm cache clean --force
    - uses: akv-platform/setup-node@add-caching-for-node-dependencies
      with:
        node-version: ${{ matrix.version }}
        cache: npm
    - name: Node version
      shell: pwsh
      run: node --version
    - name: Yarn version
      run: yarn --version
    - name: Npm version
      shell: pwsh
      run: npm --version
    - name: Install dependencies
      run: npm install
